import asyncio
import os
import re
import time
from urllib.parse import urlparse

import httpx
import structlog

log = structlog.get_logger()

GITHUB_API = "https://api.github.com"
BRANCH_PREFIX = "codemark/optimize"

CODEMARK_BOT_TOKEN = os.environ.get("CODEMARK_BOT_TOKEN", "")


def _parse_owner_repo(repo_url: str) -> tuple[str, str]:
    """Extract (owner, repo) from a GitHub URL."""
    path = urlparse(str(repo_url)).path.strip("/")
    path = re.sub(r"\.git$", "", path)
    parts = path.split("/")
    if len(parts) < 2:
        raise ValueError(f"Cannot parse owner/repo from URL: {repo_url}")
    return parts[0], parts[1]


def _build_headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _build_pr_body(comparison: dict) -> str:
    """Build a markdown PR body from the comparison report."""
    score = comparison.get("benchy_score", {})
    functions = comparison.get("functions", [])
    summary = comparison.get("summary", "")
    sandbox = comparison.get("sandbox_specs", "")

    before = score.get("overall_before", 0)
    after = score.get("overall_after", 0)

    lines = [
        "## CodeMark Optimization Report",
        "",
        f"**CodeMark Score:** {before:.0f} → {after:.0f}",
        "",
        f"| Sub-score | Value |",
        f"|-----------|-------|",
        f"| Time | {score.get('time_score', 0):.0f} |",
        f"| Memory | {score.get('memory_score', 0):.0f} |",
        f"| Complexity | {score.get('complexity_score', 0):.0f} |",
        "",
    ]

    if functions:
        lines.append("### Per-function breakdown")
        lines.append("")
        lines.append("| Function | File | Time (before → after) | Speedup | Memory Δ |")
        lines.append("|----------|------|-----------------------|---------|----------|")
        for fn in functions:
            name = fn.get("function_name", "?")
            file = fn.get("file", "?")
            old_t = fn.get("old_time_ms", 0)
            new_t = fn.get("new_time_ms", 0)
            speedup = fn.get("speedup_factor", 0)
            mem_pct = fn.get("memory_reduction_pct", 0)
            lines.append(
                f"| `{name}` | `{file}` | {old_t:.2f}ms → {new_t:.2f}ms | {speedup:.1f}x | {mem_pct:+.1f}% |"
            )
        lines.append("")

    if summary:
        lines.append("### Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    if sandbox:
        lines.append(f"<details><summary>Sandbox environment</summary>\n\n{sandbox}\n\n</details>")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [CodeMark](https://github.com/genai-genisis/codemark)*")

    return "\n".join(lines)


async def _get_bot_username(client: httpx.AsyncClient, headers: dict[str, str]) -> str:
    """Get the authenticated username for the bot token."""
    resp = await client.get(f"{GITHUB_API}/user", headers=headers)
    resp.raise_for_status()
    return resp.json()["login"]


async def _invite_bot_as_collaborator(
    client: httpx.AsyncClient,
    owner: str,
    repo: str,
    bot_username: str,
    user_token: str,
) -> bool:
    """Use the user's token to invite the bot, then the bot token to accept.

    Returns True if the bot now has push access, False on any failure.
    """
    user_headers = _build_headers(user_token)
    bot_headers = _build_headers(CODEMARK_BOT_TOKEN)

    # Step 1: Invite bot as a collaborator with push (write) permission
    invite_resp = await client.put(
        f"{GITHUB_API}/repos/{owner}/{repo}/collaborators/{bot_username}",
        headers=user_headers,
        json={"permission": "push"},
    )
    if invite_resp.status_code == 204:
        log.info("bot_already_collaborator", owner=owner, repo=repo, bot=bot_username)
        return True
    if invite_resp.status_code not in (200, 201):
        log.warning(
            "bot_invite_failed",
            owner=owner,
            repo=repo,
            bot=bot_username,
            status=invite_resp.status_code,
            body=invite_resp.text[:300],
        )
        return False

    log.info("bot_invite_sent", owner=owner, repo=repo, bot=bot_username)

    # Step 2: Find and accept the pending invitation using the bot's token
    invitations_resp = await client.get(
        f"{GITHUB_API}/user/repository_invitations",
        headers=bot_headers,
    )
    if invitations_resp.status_code != 200:
        log.warning("bot_list_invitations_failed", status=invitations_resp.status_code)
        return False

    invitation_id = None
    for inv in invitations_resp.json():
        inv_repo = inv.get("repository", {}).get("full_name", "")
        if inv_repo == f"{owner}/{repo}":
            invitation_id = inv["id"]
            break

    if invitation_id is None:
        log.warning("bot_invitation_not_found", owner=owner, repo=repo)
        return False

    accept_resp = await client.patch(
        f"{GITHUB_API}/user/repository_invitations/{invitation_id}",
        headers=bot_headers,
    )
    if accept_resp.status_code not in (200, 204):
        log.warning(
            "bot_accept_invitation_failed",
            invitation_id=invitation_id,
            status=accept_resp.status_code,
        )
        return False

    log.info("bot_invitation_accepted", owner=owner, repo=repo, bot=bot_username)
    return True


async def _ensure_fork(
    client: httpx.AsyncClient,
    headers: dict[str, str],
    owner: str,
    repo: str,
    bot_username: str,
) -> str:
    """Ensure a fork of owner/repo exists under the bot account.

    Returns the fork's full_name (e.g. "benchy-bot/portfolio-2").
    GitHub's fork API is idempotent — calling it on an existing fork returns it.
    """
    resp = await client.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/forks",
        headers=headers,
        json={"default_branch_only": True},
    )
    if resp.status_code not in (200, 202):
        resp.raise_for_status()

    fork_data = resp.json()
    fork_full_name = fork_data["full_name"]
    fork_owner = fork_data["owner"]["login"]
    log.info("bot_fork_ensured", fork=fork_full_name, fork_owner=fork_owner)

    for attempt in range(12):
        check = await client.get(
            f"{GITHUB_API}/repos/{fork_owner}/{repo}",
            headers=headers,
        )
        if check.status_code == 200:
            return fork_full_name
        await asyncio.sleep(5)

    return fork_full_name


async def _resolve_token_and_strategy(
    owner: str, repo: str, user_token: str
) -> tuple[str, bool, bool]:
    """Determine which token to use and whether to fork.

    Returns (token, is_bot, use_fork).

    Priority order:
    1. Bot already has push access → bot token, direct push.
    2. Bot exists but no push → invite bot as collaborator via user's token.
       If invitation succeeds → bot token, direct push.
    3. Public repo, invitation failed → bot token via fork.
    4. Private repo, invitation failed → user token (can't fork private repos).
    5. Bot token has no access at all → user token.
    """
    if not CODEMARK_BOT_TOKEN:
        return user_token, False, False

    async with httpx.AsyncClient(timeout=15.0) as client:
        bot_headers = _build_headers(CODEMARK_BOT_TOKEN)

        # Check current bot access level
        resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}",
            headers=bot_headers,
        )

        if resp.status_code != 200:
            # Bot can't even see the repo — try to invite it anyway (works for
            # private repos the user owns where the bot has zero prior access).
            bot_username = await _get_bot_username(client, bot_headers)
            invited = await _invite_bot_as_collaborator(
                client, owner, repo, bot_username, user_token,
            )
            if invited:
                log.info("bot_granted_access_via_invite", owner=owner, repo=repo)
                # Wait a moment for GitHub to sync permissions
                await asyncio.sleep(2)
                return CODEMARK_BOT_TOKEN, True, False

            log.warning("bot_token_no_repo_access", owner=owner, repo=repo, status=resp.status_code)
            return user_token, False, False

        repo_data = resp.json()
        permissions = repo_data.get("permissions", {})
        is_private = repo_data.get("private", False)

        if permissions.get("push"):
            return CODEMARK_BOT_TOKEN, True, False

        # Bot can see the repo but can't push — try to upgrade via invitation
        bot_username = await _get_bot_username(client, bot_headers)
        invited = await _invite_bot_as_collaborator(
            client, owner, repo, bot_username, user_token,
        )
        if invited:
            log.info("bot_upgraded_to_push_via_invite", owner=owner, repo=repo)
            # Wait a moment for GitHub to sync permissions
            await asyncio.sleep(2)
            return CODEMARK_BOT_TOKEN, True, False

        # Invitation failed — fork for public repos, user token for private
        if is_private:
            log.info(
                "bot_no_push_private_repo_fallback",
                owner=owner,
                repo=repo,
                reason="invitation failed and cannot fork private repos",
            )
            return user_token, False, False

        log.info("bot_no_push_will_fork", owner=owner, repo=repo)
        return CODEMARK_BOT_TOKEN, True, True


async def _push_changes_to_repo(
    client: httpx.AsyncClient,
    headers: dict[str, str],
    target_repo: str,
    branch_name: str,
    base_sha: str,
    optimized_files: dict[str, str],
) -> None:
    """Create branch, blobs, tree, commit, and update ref on the target repo."""
    create_ref_resp = await client.post(
        f"{GITHUB_API}/repos/{target_repo}/git/refs",
        headers=headers,
        json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
    )
    if create_ref_resp.status_code != 201:
        log.error("pr_branch_create_failed", status=create_ref_resp.status_code, text=create_ref_resp.text)
    create_ref_resp.raise_for_status()
    log.info("pr_branch_created", repo=target_repo, branch=branch_name)

    blob_shas: dict[str, str] = {}
    for file_path, content in optimized_files.items():
        blob_resp = await client.post(
            f"{GITHUB_API}/repos/{target_repo}/git/blobs",
            headers=headers,
            json={"content": content, "encoding": "utf-8"},
        )
        if blob_resp.status_code != 201:
            log.error("pr_blob_create_failed", path=file_path, status=blob_resp.status_code, text=blob_resp.text)
        blob_resp.raise_for_status()
        blob_shas[file_path] = blob_resp.json()["sha"]

    commit_resp = await client.get(
        f"{GITHUB_API}/repos/{target_repo}/git/commits/{base_sha}",
        headers=headers,
    )
    commit_resp.raise_for_status()
    base_tree_sha = commit_resp.json()["tree"]["sha"]

    tree_items = [
        {"path": path, "mode": "100644", "type": "blob", "sha": sha}
        for path, sha in blob_shas.items()
    ]
    tree_resp = await client.post(
        f"{GITHUB_API}/repos/{target_repo}/git/trees",
        headers=headers,
        json={"base_tree": base_tree_sha, "tree": tree_items},
    )
    tree_resp.raise_for_status()
    new_tree_sha = tree_resp.json()["sha"]

    commit_payload: dict = {
        "message": "perf: CodeMark automated optimizations",
        "tree": new_tree_sha,
        "parents": [base_sha],
        "author": {
            "name": "CodeMark",
            "email": "codemark-bot@users.noreply.github.com",
        },
    }
    new_commit_resp = await client.post(
        f"{GITHUB_API}/repos/{target_repo}/git/commits",
        headers=headers,
        json=commit_payload,
    )
    new_commit_resp.raise_for_status()
    new_commit_sha = new_commit_resp.json()["sha"]

    update_ref_resp = await client.patch(
        f"{GITHUB_API}/repos/{target_repo}/git/refs/heads/{branch_name}",
        headers=headers,
        json={"sha": new_commit_sha},
    )
    update_ref_resp.raise_for_status()


async def create_optimization_pr(
    repo_url: str,
    github_token: str,
    optimized_files: dict[str, str],
    comparison: dict,
) -> str:
    """Create a GitHub PR with the optimized code changes.

    Strategy:
    1. If the bot token has direct push access → push branch and open PR directly.
    2. If the bot token exists but lacks push → fork the repo under the bot account,
       push to the fork, and open a cross-fork PR.
    3. No bot token → use the user's token directly.

    Returns the PR HTML URL on success, or an empty string on failure.
    """
    if not optimized_files:
        log.warning("create_pr_skipped", reason="no optimized files")
        return ""

    owner, repo = _parse_owner_repo(repo_url)
    branch_name = f"{BRANCH_PREFIX}-{int(time.time())}"

    token, is_bot, use_fork = await _resolve_token_and_strategy(owner, repo, github_token)
    log.info("create_pr_token_resolved", is_bot=is_bot, use_fork=use_fork)

    headers = _build_headers(token)

    async with httpx.AsyncClient(timeout=30.0) as client:
        scope_check = await client.get(f"{GITHUB_API}/user", headers=headers)
        scopes = scope_check.headers.get("x-oauth-scopes", "(not present)")
        log.info("token_scopes", scopes=scopes, is_bot=is_bot)

        # Resolve base SHA from the upstream repo (always use user token for reading
        # the upstream so we don't depend on fork sync state).
        upstream_headers = _build_headers(github_token)
        repo_resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}",
            headers=upstream_headers,
        )
        repo_resp.raise_for_status()
        repo_data = repo_resp.json()
        default_branch = repo_data["default_branch"]
        permissions = repo_data.get("permissions", {})
        log.info(
            "pr_repo_permissions",
            owner=owner,
            repo=repo,
            permissions=permissions,
            is_bot=is_bot,
        )

        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{default_branch}",
            headers=upstream_headers,
        )
        ref_resp.raise_for_status()
        base_sha = ref_resp.json()["object"]["sha"]

        log.info(
            "pr_base_resolved",
            owner=owner,
            repo=repo,
            default_branch=default_branch,
            base_sha=base_sha[:8],
        )

        if use_fork:
            bot_username = await _get_bot_username(client, headers)
            fork_full_name = await _ensure_fork(client, headers, owner, repo, bot_username)
            push_repo = fork_full_name
            pr_head = f"{bot_username}:{branch_name}"
        else:
            if not is_bot and not permissions.get("push"):
                log.error(
                    "user_token_no_push_access",
                    owner=owner,
                    repo=repo,
                    permissions=permissions,
                )
                raise PermissionError(
                    f"GitHub token does not have push access to {owner}/{repo}. "
                    "Please revoke and re-authorize the app at https://github.com/settings/applications "
                    "to grant the 'repo' scope."
                )
            push_repo = f"{owner}/{repo}"
            pr_head = branch_name

        log.info("pr_pushing_changes", push_repo=push_repo, branch=branch_name)
        await _push_changes_to_repo(
            client, headers, push_repo, branch_name, base_sha, optimized_files,
        )

        pr_body = _build_pr_body(comparison)
        pr_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
            headers=headers,
            json={
                "title": "perf: CodeMark automated optimizations",
                "head": pr_head,
                "base": default_branch,
                "body": pr_body,
            },
        )
        pr_resp.raise_for_status()
        pr_url = pr_resp.json()["html_url"]

        log.info("pr_created", pr_url=pr_url, files=len(optimized_files), use_fork=use_fork)
        return pr_url
