import re
import time
from urllib.parse import urlparse

import httpx
import structlog

log = structlog.get_logger()

GITHUB_API = "https://api.github.com"
BRANCH_PREFIX = "codemark/optimize"


def _parse_owner_repo(repo_url: str) -> tuple[str, str]:
    """Extract (owner, repo) from a GitHub URL."""
    path = urlparse(str(repo_url)).path.strip("/")
    path = re.sub(r"\.git$", "", path)
    parts = path.split("/")
    if len(parts) < 2:
        raise ValueError(f"Cannot parse owner/repo from URL: {repo_url}")
    return parts[0], parts[1]


def _build_headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _build_pr_body(comparison: dict) -> str:
    """Build a markdown PR body from the comparison report."""
    score = comparison.get("codemark_score", {})
    functions = comparison.get("functions", [])
    summary = comparison.get("summary", "")
    sandbox = comparison.get("sandbox_specs", "")

    before = score.get("overall_before", 0)
    after = score.get("overall_after", 0)

    lines = [
        "## CodeMark Optimization Report",
        "",
        f"**CodeMark Score:** {before:.0f} → {after:.0f}",
        "",
        f"| Sub-score | Value |",
        f"|-----------|-------|",
        f"| Time | {score.get('time_score', 0):.0f} |",
        f"| Memory | {score.get('memory_score', 0):.0f} |",
        f"| Complexity | {score.get('complexity_score', 0):.0f} |",
        "",
    ]

    if functions:
        lines.append("### Per-function breakdown")
        lines.append("")
        lines.append("| Function | File | Time (before → after) | Speedup | Memory Δ |")
        lines.append("|----------|------|-----------------------|---------|----------|")
        for fn in functions:
            name = fn.get("function_name", "?")
            file = fn.get("file", "?")
            old_t = fn.get("old_time_ms", 0)
            new_t = fn.get("new_time_ms", 0)
            speedup = fn.get("speedup_factor", 0)
            mem_pct = fn.get("memory_reduction_pct", 0)
            lines.append(
                f"| `{name}` | `{file}` | {old_t:.2f}ms → {new_t:.2f}ms | {speedup:.1f}x | {mem_pct:+.1f}% |"
            )
        lines.append("")

    if summary:
        lines.append("### Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    if sandbox:
        lines.append(f"<details><summary>Sandbox environment</summary>\n\n{sandbox}\n\n</details>")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [CodeMark](https://github.com/genai-genisis/codemark)*")

    return "\n".join(lines)


async def create_optimization_pr(
    repo_url: str,
    github_token: str,
    optimized_files: dict[str, str],
    comparison: dict,
) -> str:
    """Create a GitHub PR with the optimized code changes.

    Returns the PR HTML URL on success, or an empty string on failure.
    """
    if not optimized_files:
        log.warning("create_pr_skipped", reason="no optimized files")
        return ""

    owner, repo = _parse_owner_repo(repo_url)
    headers = _build_headers(github_token)
    branch_name = f"{BRANCH_PREFIX}-{int(time.time())}"

    async with httpx.AsyncClient(timeout=30.0) as client:
        # 1. Get default branch and its latest commit SHA
        repo_resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}",
            headers=headers,
        )
        repo_resp.raise_for_status()
        default_branch = repo_resp.json()["default_branch"]

        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/ref/heads/{default_branch}",
            headers=headers,
        )
        ref_resp.raise_for_status()
        base_sha = ref_resp.json()["object"]["sha"]

        log.info(
            "pr_base_resolved",
            owner=owner,
            repo=repo,
            default_branch=default_branch,
            base_sha=base_sha[:8],
        )

        # 2. Create branch
        create_ref_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
        )
        create_ref_resp.raise_for_status()
        log.info("pr_branch_created", branch=branch_name)

        # 3. Create blobs for each optimized file
        blob_shas: dict[str, str] = {}
        for file_path, content in optimized_files.items():
            blob_resp = await client.post(
                f"{GITHUB_API}/repos/{owner}/{repo}/git/blobs",
                headers=headers,
                json={"content": content, "encoding": "utf-8"},
            )
            blob_resp.raise_for_status()
            blob_shas[file_path] = blob_resp.json()["sha"]

        # 4. Get the base tree
        commit_resp = await client.get(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/commits/{base_sha}",
            headers=headers,
        )
        commit_resp.raise_for_status()
        base_tree_sha = commit_resp.json()["tree"]["sha"]

        # 5. Create a new tree with the changed files
        tree_items = [
            {
                "path": path,
                "mode": "100644",
                "type": "blob",
                "sha": sha,
            }
            for path, sha in blob_shas.items()
        ]
        tree_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/trees",
            headers=headers,
            json={"base_tree": base_tree_sha, "tree": tree_items},
        )
        tree_resp.raise_for_status()
        new_tree_sha = tree_resp.json()["sha"]

        # 6. Create a commit on the new tree
        new_commit_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/commits",
            headers=headers,
            json={
                "message": "perf: CodeMark automated optimizations",
                "tree": new_tree_sha,
                "parents": [base_sha],
            },
        )
        new_commit_resp.raise_for_status()
        new_commit_sha = new_commit_resp.json()["sha"]

        # 7. Point the branch at the new commit
        update_ref_resp = await client.patch(
            f"{GITHUB_API}/repos/{owner}/{repo}/git/refs/heads/{branch_name}",
            headers=headers,
            json={"sha": new_commit_sha},
        )
        update_ref_resp.raise_for_status()

        # 8. Open the pull request
        pr_body = _build_pr_body(comparison)
        pr_resp = await client.post(
            f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
            headers=headers,
            json={
                "title": "perf: CodeMark automated optimizations",
                "head": branch_name,
                "base": default_branch,
                "body": pr_body,
            },
        )
        pr_resp.raise_for_status()
        pr_url = pr_resp.json()["html_url"]

        log.info("pr_created", pr_url=pr_url, files=len(optimized_files))
        return pr_url
